openapi: 3.0.3
info:
  title: Population Import Service
  version: 1.0.0
  description: API для импорта данных о населении и получения данных по странам.

servers:
  - url: http://localhost:8080/api/v1

paths:
  /api/v1/import:
    post:
      summary: Запуск импорта данных о населении
      operationId: startImport
      responses:
        '202':
          description: Импорт запущен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportResult'
        '500':
          description: Внутренняя ошибка сервера

  /api/v1/import/{job_id}:
    get:
      summary: Получить статус задачи импорта по ID
      operationId: getImportJobStatus
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
          description: ID задачи импорта
      responses:
        '200':
          description: Статус задачи импорта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportJobStatus'
        '404':
          description: Задача не найдена
        '500':
          description: Внутренняя ошибка сервера

  /api/v1/population/{country_code}:
    get:
      summary: Получить данные о населении по коду страны
      operationId: getPopulationByCountry
      parameters:
        - name: country_code
          in: path
          required: true
          schema:
            type: string
          description: Трёхбуквенный код страны (ISO 3166-1 alpha-3)
      responses:
        '200':
          description: Список данных по населению
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PopulationEntry'
        '404':
          description: Данные не найдены
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:
    ImportResult:
      type: object
      properties:
        job_id:
          type: string
          description: ID созданной задачи импорта
        status:
          type: string
          description: Статус задачи импорта
          enum: [pending, in_progress, completed, failed]
      required:
        - job_id
        - status

    ImportJobStatus:
      type: object
      properties:
        job_id:
          type: string
          description: ID задачи импорта
        status:
          type: string
          description: Статус задачи импорта
          enum: [pending, in_progress, completed, failed]
        started_at:
          type: string
          format: date-time
          description: Время начала задачи
        finished_at:
          type: string
          format: date-time
          description: Время завершения задачи (если завершена)
        total_rows:
          type: integer
          description: Общее количество обработанных строк
        saved_rows:
          type: integer
          description: Количество сохраненных строк
        failed_rows:
          type: integer
          description: Количество строк с ошибками
        duration_ms:
          type: integer
          description: Время выполнения в миллисекундах
        error:
          type: string
          description: Сообщение об ошибке (если есть)
      required:
        - job_id
        - status
        - started_at

    PopulationEntry:
      type: object
      properties:
        country_name:
          type: string
        country_code:
          type: string
        year:
          type: integer
        population:
          type: integer
      required:
        - country_name
        - country_code
        - year
        - population