openapi: 3.0.3
info:
  title: Population Import Service
  version: 1.0.0
  description: API для импорта данных о населении и получения данных по странам.

servers:
  - url: http://localhost:8080/api/v1

paths:
  /api/v1/import:
    post:
      summary: Запуск импорта данных о населении
      operationId: startImport
      responses:
        '202':
          description: Импорт запущен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportResult'
        '500':
          description: Внутренняя ошибка сервера

  /api/v1/population/{country_code}:
    get:
      summary: Получить данные о населении по коду страны
      operationId: getPopulationByCountry
      parameters:
        - name: country_code
          in: path
          required: true
          schema:
            type: string
          description: Трёхбуквенный код страны (ISO 3166-1 alpha-3)
      responses:
        '200':
          description: Список данных по населению
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PopulationEntry'
        '404':
          description: Данные не найдены
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:
    ImportResult:
      type: object
      properties:
        total_rows:
          type: integer
        saved_rows:
          type: integer
        failed_rows:
          type: integer
      required:
        - total_rows
        - saved_rows
        - failed_rows

    PopulationEntry:
      type: object
      properties:
        country_name:
          type: string
        country_code:
          type: string
        year:
          type: integer
        population:
          type: integer
      required:
        - country_name
        - country_code
        - year
        - population